#
# Global setting
###########################################
spring:
  profiles:
    active: local
  application:
    name: enbiz-api-sample
  web:
    locale: ko
  messages:
    basename:
      message.common.common
  cache:
    jcache:
      config: classpath:ehcache.xml
  autoconfigure:
    exclude: org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration

mybatis:
  type-aliases-package: com.enbiz.api.common.app
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

management:
  health:
    defaults:
      enabled: false
  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

---
#
# LOCAL Setting
###########################################
server:
  port: 8090
  servlet:
    context-path: /api/sample

spring:
  config:
    activate:
      on-profile: local
  zipkin:
    enabled: false
  devtools:
    livereload:
      port: 3${server.port}
  datasource:
    main:
      #jdbc-url: jdbc:postgresql://thm-dev-product-cluster.cluster-ro-c8ozhq4tkh6g.ap-northeast-2.rds.amazonaws.com:5432/thehandsome?currentSchema=pd_adm
      jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/postgres?currentSchema=public
      #driver-class-name: org.postgresql.Driver
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy    
      username: enbiz
      password: ENC(HrUDmfNQe8eFLPyowYesfad3oA9h3Rt5mGX8EkzNJBtVnC/FDw7X/ZQHr4E7xB6f)
      hikari:
        maximum-pool-size: 5
        minimum-idle: 5
        connection-timeout: 30000
        validation-timeout: 5000
        max-lifetime: 1800000
        idle-timeout: 300000
    replica:
      #jdbc-url: jdbc:postgresql://thm-dev-product-cluster.cluster-c8ozhq4tkh6g.ap-northeast-2.rds.amazonaws.com:5432/thehandsome?currentSchema=pd_adm
      jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/postgres?currentSchema=public
      #driver-class-name: org.postgresql.Driver
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy    
      username: enbiz
      password: ENC(HrUDmfNQe8eFLPyowYesfad3oA9h3Rt5mGX8EkzNJBtVnC/FDw7X/ZQHr4E7xB6f)
      hikari:
        maximum-pool-size: 5
        minimum-idle: 5
        connection-timeout: 30000
        validation-timeout: 5000
        max-lifetime: 1800000
        idle-timeout: 300000

springfox:
  documentation:
    enabled: true

jwt:
  service:      
    key: ENC(tkX4ef+7zT0vEAj5TF+7CIMQL2AsFw58DXwAHlXCbStu0o5yHMuL2ttMjYN1y7Mfn1eH1ok9yl1OWdeUHyVm+g==)
  member:
    access:
      key: ENC(aI9Usg3VdYZ0Raix7soouBIuKI+mzWWEpELiOK/SRL1xiB7uyeUcyrtIubW1HLeH8Inrg45ONOHmgcSzV+ctyiLBIfaf5I6K23ibDwSTmZA=)
    refresh:
      key: ENC(ZAIbzXfpATW+dMgLktdfigyr+65q/N+VAPqcrTGVMpnPuaW7g2EfR/4p/KPE1EWsQTRujWmjtxuwtudbdXJNyNibT6/sNSkBxZlMk98RUcQ=)

jasypt:
  encryptor:
    password: local # PROD 환경에서는 환경변수 통해 값을 넣어줄것. 
          
---
#
# DEV Setting
###########################################
server:
  port: 9022
  servlet:
    context-path: /api/sample

spring:
  config:
    activate:
      on-profile: dev

jwt:
  service:      
    key: ENC(tkX4ef+7zT0vEAj5TF+7CIMQL2AsFw58DXwAHlXCbStu0o5yHMuL2ttMjYN1y7Mfn1eH1ok9yl1OWdeUHyVm+g==)
  member:
    access:
      key: ENC(aI9Usg3VdYZ0Raix7soouBIuKI+mzWWEpELiOK/SRL1xiB7uyeUcyrtIubW1HLeH8Inrg45ONOHmgcSzV+ctyiLBIfaf5I6K23ibDwSTmZA=)
    refresh:
      key: ENC(ZAIbzXfpATW+dMgLktdfigyr+65q/N+VAPqcrTGVMpnPuaW7g2EfR/4p/KPE1EWsQTRujWmjtxuwtudbdXJNyNibT6/sNSkBxZlMk98RUcQ=)

jasypt:
  encryptor:
    password: local
          